# file name: eso-external-secret-to-pull-from-dev0-to-dev1.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example-pull-secret
spec:
  refreshInterval: 1h           
  secretStoreRef:
    kind: SecretStore
    name: eso-example      # name of the SecretStore 
  target:
    name: secret-example   # name of the k8s Secret to be created in kind-dev1 once pulled from kind-dev0
    creationPolicy: Owner  # Overwrites/deletes manual edits
  data:
  - secretKey: extra
    remoteRef:
      key: secret-example
      property: extra