apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: eso-example
spec:
  provider:
      kubernetes:
        remoteNamespace: eso-demo
        server: 
          url: https://dev0-control-plane:6443
          caProvider: 
            type: Secret
            name : dev0-cluster-secrets       # name of the secret with the dev0 certificate
            key: certificate-authority-data   # key from the secret with the dev0 certificate
        auth:
          cert:
            clientCert: 
                name: dev0-cluster-secrets    # name of the secret with the dev0 certificate
                key: client-certificate-data  # key from the secret with the dev0 certificate
            clientKey: 
                name: dev0-cluster-secrets    # name of the secret with the dev0 certificate
                key: client-key-data          # key from the secret with the dev0 certificate