- name: Pre-check tools for helm and kubectl
  ansible.builtin.include_tasks: check-clis.yml

- name: Execute file operations with guaranteed cleanup
  block:
    - name: Copy file to remote tmp directory
      ansible.builtin.copy:
        src: "{{ local_file_path }}"
        dest: "{{ dest_file_path }}"
        mode: '0644'

    - name: Verify the file exists on the remote system
      ansible.builtin.stat:
        path: "{{ dest_file_path }}"
      register: file_status
    
    - name: Display file copy confirmation details
      ansible.builtin.debug:
        msg: >
          File exists: {{ file_status.stat.exists }}. 
          Size: {{ file_status.stat.size }} bytes. 
          Owner: {{ file_status.stat.pw_name }}.
      failed_when: not file_status.stat.exists

    - name: List all files in the target folder
      ansible.builtin.command: "ls {{ dest_file_path }}"
      register: folder_contents

    - name: Create namespace for seaweedfs cluster
      ansible.builtin.command: "kubectl create namespace {{ seaweedfs_cluster_namespace }}"
      register: kubectl_create_ns_result
      changed_when: "'created' in kubectl_create_ns_result.stdout"
      failed_when: "'AlreadyExists' not in kubectl_create_ns_result.stderr and kubectl_create_ns_result.rc != 0"

    - name: Print command to execute
      ansible.builtin.debug:
         msg: |
          "Command to install Seaweedfs cluster:"
          "kubectl apply -f {{ dest_file_path }}/{{ seaweed_cluster_file }} -n {{ seaweedfs_cluster_namespace }}"

    - name: Install service account
      ansible.builtin.command: "kubectl apply -f {{ dest_file_path }}/{{ service_account_file }} -n {{ seaweedfs_cluster_namespace }} "
      register: service_acct_result
      changed_when: "'created' in service_acct_result.stdout or 'configured' in service_acct_result.stdout"

    - name: Print output status
      ansible.builtin.debug:
         msg: |
          "Service account: {{ service_acct_result.stdout }}"

    - name: Install the SeaweedFS cluster
      ansible.builtin.command: "kubectl apply -f {{ dest_file_path }}/{{ seaweed_cluster_file }} -n {{ seaweedfs_cluster_namespace }}"
      register: kubectl_clstr_result
      changed_when: "'created' in kubectl_clstr_result.stdout or 'configured' in kubectl_clstr_result.stdout"

    - name: Print the output of install command
      ansible.builtin.debug:
         msg: "Install command: {{ kubectl_clstr_result  }}"

    - name: List all resources in the SeaweedFS cluster namespace
      ansible.builtin.command: "kubectl get {{item}} -n {{ seaweedfs_cluster_namespace }}"
      register: sw_cluster_result
      loop: "{{ seaweedfs_cluster_resources }}"

    - name: Print output of all resources
      ansible.builtin.debug:
        msg: |
         "Resource output: {{ item.item }} status {{ item.rc }}"
      loop: "{{ sw_cluster_result.results }}"

  always:
    - name: Clean up and remove the remote temporary file
      ansible.builtin.file:
        path: "{{ dest_file_path }}"
        state: absent