#server:
#  port: 8080

spring:
   application:
     name: item-mcp-server
   main:
      #web-application-type: none
      banner-mode: off
   ai:
     mcp:
        server:
           name: item-mcp-server
           version: 1.0.0

logging:
   pattern:
      console:
   level:
      root: info