---
- name: "Check Kind cli exists"
  ansible.builtin.include_tasks: 
    file: "check.yml"
    apply:
      tags: [kind-cli-check, kind-check]
  tags:
     - kind-cli-check
     - kind-check

- name: "Install Kind cli"
  ansible.builtin.include_tasks: 
    file: "install-cli.yml"
    apply:
      tags: [kind-cli-install, kind-install]
  tags:
     - kind-cli-install
     - kind-install

- name: "Install Kind cluster"
  ansible.builtin.include_tasks: 
    file: "install-cluster.yml"
    apply:
      tags: [kind-cluster-install, kind-cluster]
  tags:
     - kind-cluster-install
     - kind-cluster

#  tags: [always]
#- name: "kind cli {{ role_action | default('install') }}"
#  ansible.builtin.include_tasks: {{ role_action | default('install') }}
#  apply:
#    tags: [kind-install]
#  tags: [always]