CREATE SEQUENCE IF NOT EXISTS ORDER_SEQ MINVALUE 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS ORDER_INFO
 (ORDER_ID INTEGER NOT NULL,
  USER_NAME VARCHAR(45) NOT NULL,
  ORDER_TAG VARCHAR(25),
  ITEM_NAME VARCHAR(45) NOT NULL,
  ITEM_QUANTITY INTEGER NOT NULL,
  CREATED_BY VARCHAR(45) NOT NULL,
  UPDATED_BY VARCHAR(45) NOT NULL,
  CREATED_AT DATE,
  UPDATED_AT DATE,
  METADATA VARCHAR(100),
  DESCRIPTION VARCHAR(100),
  CURRENT_STATUS VARCHAR(40),
  PRIMARY KEY (ORDER_ID));

CREATE SEQUENCE IF NOT EXISTS ORDER_STATUS_SEQ MINVALUE 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS ORDER_STATUS
(ORDER_STATUS_ID INTEGER NOT NULL,
USER_NAME VARCHAR(45) NOT NULL,
ORDER_ID INTEGER NOT NULL,
STATUS VARCHAR(25) NOT NULL,
UPDATED_AT DATE,
UPDATED_BY VARCHAR(45));