///usr/bin/env jbang "$0" "$0" : exit $?

//DEPS org.apache.camel:camel-bom:4.18.1@pom
//DEPS org.apache.camel:camel-core
//DEPS org.apache.camel:camel-main
//DEPS org.apache.camel:camel-stream
//DEPS org.apache.camel:camel-kafka
//DEPS org.apache.camel:camel-jackson-avro
//DEPS org.apache.camel:camel-avro
// To skip the logs use nop dependency
// - / / DEPS org.slf4j:slf4j-nop:2.0.13
//DEPS org.slf4j:slf4j-simple:2.0.13
//DEPS org.slf4j:slf4j-api:2.0.13
//DEPS org.apache.avro:avro:1.12.1
//DEPS org.apache.avro:avro-compiler:1.12.1
//DEPS org.apache.avro:avro-maven-plugin:1.12.1
//DEPS io.apicurio:apicurio-registry-avro-serde-kafka:3.2.1

import org.apache.camel.ProducerTemplate;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.main.Main;

import java.nio.file.Files;
import java.nio.file.Path;

import java.util.List;
import java.util.ArrayList;

import static java.lang.System.out;
import static java.lang.System.setProperty;;

class AvroProducer{

    public static void main(String ... args) throws Exception{
        out.println("Starting camel route...");
        setProperty("org.slf4j.simpleLogger.logFile", "System.out");        

        Main main = new Main();

        //List of input employee info as string
        //The schema will be fetched from apicurio registry
        List<String> inputString = new ArrayList<>();

        String str1 = """
                {"name":"User1","address":{"string":"11,somewhere,country"}}
                """;
        String str2="""
                {"name":"User2","address":{"string":"12,somewhere,country"}}
                """;
        String str3="""
                {"name":"User3","address":{"string":"13,somewhere,country"}}
                """;
        String str4="""
             {"name":"User4","address":{"string":"15,somewhere,country"}}
                """;
        inputString.add(str1);
        inputString.add(str2);
        inputString.add(str3);
        inputString.add(str4);
        
        //the ca.crt content from the envrionemnt the secret
        // generated by the cert manager in the cluster
        String caCert = """
        -----BEGIN CERTIFICATE-----
        MIIDEDCCAfigAwIBAgIUN2QC7KftnYYFMq0QbDJZLIHuy88wDQYJKoZIhvcNAQEL
        BQAwIDEeMBwGA1UEAxMVYXBpY3VyaW8uYXBwLmRlbW8uY29tMB4XDTI2MDQyNjIw
        MDQyM1oXDTI2MDcyNTIwMDQyM1owIDEeMBwGA1UEAxMVYXBpY3VyaW8uYXBwLmRl
        bW8uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7M2Jhw7CjwfV
        uVSyISicjfEh8tMl0qZvr3nD1H4q0d1mAB2JJ+meulvsout8rsHIzgHgvRxKs6gU
        FZljTb+kHAXSQqNytoZ0vZoWA01s6CLcTbIphTStQZ9jkinQLGju2RMrEecLPiW6
        +JiGP66hD+NT//AmJE27+KzB5bC17YzRRf4sFsZmIntWwdZUdL2RTTjjkm2Jj08p
        97DyNby0bXBOpg18h0qrlDJfY17jlbwBA9ItqObR4FOqmwE+rYTXhCHfXKj0comO
        Pc2UrcGxaJ5mly8g+fAp+GDBo15UZkhNbzOop1iAj1K5zpZsDwczZSrhSBHv8Dv3
        vBgt0YNKSQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAg
        BgNVHREEGTAXghVhcGljdXJpby5hcHAuZGVtby5jb20wDQYJKoZIhvcNAQELBQAD
        ggEBAKk7HJCyIsRjNMPvfXpzpQkoerudvLmcncRpTWyituAIsaTYQ2EU57CBuFpO
        jlO+zTuOJKI3S/o8GOo+DNAAb2XaRQsgnXq/9YOCOsv3BC3uuEiJ5afemN4MxfrP
        pY4GXXCj+jkDd0fMSZ+sQJUUkR0b/bRhwdQwLqLmBFgdZXXglfYkrMQ3gSq95wyy
        ZGEND7QN0JWCQknGvCkI7v3h9lwnC5xN7KzS/+FlFANV6Z/eIKXKRMTgjje/+1aM
        uPj0v5Y+el1uMAGkePjyWzDs3s35CINW4dEV5T++t5/QsT+M4hmvsPUCdAfI2CgE
        48zKhAn+6un8kpt08BBlSodA81A=
        -----END CERTIFICATE-----        
        """;

       // Convert the ca cert string to file and place in temp directory
       Path caPath = Files.writeString(Files.createTempFile("ca", ".pem"), caCert);

       System.out.println("Temp path of the created certificate - "+caPath.toAbsolutePath());

       main.configure().addRoutesBuilder(new RouteBuilder(){
            public void configure() throws Exception{
        
               onException(Exception.class)
               .process(exchange -> {
                Exception cause = exchange.getException();
                cause.printStackTrace();
                System.out.println("---x[Exception occurred]x---");
               })
               .handled(true)
               .stop();

               from("direct:start")
               .split(body())
                //process prints each message from the list produced using producer template
                //.process(exchange -> System.out.println("string data:- "+exchange.getIn().getBody()))
               .log("publishing msg: ${body}")
                //check for ssl config- https://github.com/Apicurio/apicurio-registry/blob/main/schema-resolver/src/main/java/io/apicurio/registry/resolver/config/SchemaResolverConfig.java
               .to("kafka:demo-topic-1?brokers=localhost:31092"
                    + "&valueSerializer=io.apicurio.registry.serde.avro.AvroKafkaSerializer"
                    + "&additionalProperties[apicurio.registry.url]=https://apicurio.app.demo.com/apis/registry/v3"
                    + "&additionalProperties[apicurio.registry.auto-register]=true"
                    + "&additionalProperties[apicurio.registry.tls.truststore.type]=PEM"
                    + "&additionalProperties[apicurio.registry.tls.truststore.location]="+ caPath.toAbsolutePath()
                )
               .to("stream:out");

            }
         });

       //To continously produce message use run method
       //main.run();

        main.start();
        // create producer template 
        ProducerTemplate template = main.getCamelContext().createProducerTemplate();

        template.sendBody("direct:start", inputString);

        Thread.sleep(5000);
        main.stop();
    }
}