///usr/bin/env jbang "$0" "$0" : exit $?
//DEPS org.apache.camel:camel-bom:4.18.1@pom
//DEPS org.apache.camel:camel-core
//DEPS org.apache.camel:camel-main
//DEPS org.apache.camel:camel-stream
//DEPS org.apache.camel:camel-kafka
//DEPS org.apache.camel:camel-jackson-avro
//DEPS org.apache.camel:camel-avro
//DEPS org.apache.kafka:kafka-clients:4.2.0
// To skip logs from printing use the nop dependency
// -/ / DEPS org.slf4j:slf4j-nop:2.0.13
//DEPS org.slf4j:slf4j-simple:2.0.13
//DEPS org.slf4j:slf4j-api:2.0.13
//DEPS org.apache.avro:avro:1.12.1
//DEPS io.apicurio:apicurio-registry-avro-serde-kafka:3.2.2

import java.nio.file.Files;
import java.nio.file.Path;
import org.apache.camel.builder.*;
import org.apache.camel.main.*;
import static java.lang.System.*;

class AvroConsumer{

    public static void main(String ... args) throws Exception{
        out.println("Starting camel route...");
        setProperty("org.slf4j.simpleLogger.logFile", "System.out");
        setProperty("org.slf4j.simpleLogger.defaultLogLevel", "info");
        setProperty("org.slf4j.simpleLogger.log.org.apache.camel", "info");

        Main main = new Main();

        //the ca.crt content from the envrionemnt the secret
        // generated by the cert manager in the cluster 
        String caCert = """
        -----BEGIN CERTIFICATE-----
        MIIDEDCCAfigAwIBAgIUN2QC7KftnYYFMq0QbDJZLIHuy88wDQYJKoZIhvcNAQEL
        BQAwIDEeMBwGA1UEAxMVYXBpY3VyaW8uYXBwLmRlbW8uY29tMB4XDTI2MDQyNjIw
        MDQyM1oXDTI2MDcyNTIwMDQyM1owIDEeMBwGA1UEAxMVYXBpY3VyaW8uYXBwLmRl
        bW8uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7M2Jhw7CjwfV
        uVSyISicjfEh8tMl0qZvr3nD1H4q0d1mAB2JJ+meulvsout8rsHIzgHgvRxKs6gU
        FZljTb+kHAXSQqNytoZ0vZoWA01s6CLcTbIphTStQZ9jkinQLGju2RMrEecLPiW6
        +JiGP66hD+NT//AmJE27+KzB5bC17YzRRf4sFsZmIntWwdZUdL2RTTjjkm2Jj08p
        97DyNby0bXBOpg18h0qrlDJfY17jlbwBA9ItqObR4FOqmwE+rYTXhCHfXKj0comO
        Pc2UrcGxaJ5mly8g+fAp+GDBo15UZkhNbzOop1iAj1K5zpZsDwczZSrhSBHv8Dv3
        vBgt0YNKSQIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCBaAwDAYDVR0TAQH/BAIwADAg
        BgNVHREEGTAXghVhcGljdXJpby5hcHAuZGVtby5jb20wDQYJKoZIhvcNAQELBQAD
        ggEBAKk7HJCyIsRjNMPvfXpzpQkoerudvLmcncRpTWyituAIsaTYQ2EU57CBuFpO
        jlO+zTuOJKI3S/o8GOo+DNAAb2XaRQsgnXq/9YOCOsv3BC3uuEiJ5afemN4MxfrP
        pY4GXXCj+jkDd0fMSZ+sQJUUkR0b/bRhwdQwLqLmBFgdZXXglfYkrMQ3gSq95wyy
        ZGEND7QN0JWCQknGvCkI7v3h9lwnC5xN7KzS/+FlFANV6Z/eIKXKRMTgjje/+1aM
        uPj0v5Y+el1uMAGkePjyWzDs3s35CINW4dEV5T++t5/QsT+M4hmvsPUCdAfI2CgE
        48zKhAn+6un8kpt08BBlSodA81A=
        -----END CERTIFICATE-----        
        """;

       Path caPath = Files.writeString(Files.createTempFile("ca", ".pem"), caCert);
       System.out.println("certificate path "+caPath.toAbsolutePath());

        main.configure().addRoutesBuilder(new RouteBuilder(){
            public void configure() throws Exception{

               onException(Exception.class)
               .process(exchange -> {
                Exception cause = exchange.getException();
                System.out.println(cause.getMessage());
                   cause.printStackTrace();
               System.out.println("--x[Exception occurred]x--");
               })
               .handled(true)
               .stop();

                from("kafka:demo-topic-1?brokers=localhost:31092" 
                    +"&maxPollRecords=1000&consumersCount=1"
                    +"&seekTo=BEGINNING"
                    +"&groupId=kafka-group-id"
                    //random groupid generation
                    //+"&groupId=${bean:java.util.UUID?method=randomUUID}" 
                    +"&valueDeserializer=io.apicurio.registry.serde.avro.AvroKafkaDeserializer" 
                    + "&keyDeserializer=org.apache.kafka.common.serialization.StringDeserializer"
                    +"&additionalProperties[apicurio.registry.url]=https://apicurio.app.demo.com/apis/registry/v3" 
                    +"&additionalProperties[apicurio.registry.auto-register]=true" 
                    +"&additionalProperties[apicurio.registry.tls.truststore.type]=PEM"
                    +"&additionalProperties[apicurio.registry.tls.truststore.location]="+ caPath.toAbsolutePath() 
                )
                //process to print the message that is consumed from the kafka topic
                //.process(exchange -> System.out.println("Msg from exchange - "+exchange.getIn().getBody()))
                .log("Consumed Avro Message: ${body}")
                .to("stream:out");
            }
         });
        //with run continously polls 
        //main.run();
        main.start();
        Thread.sleep(10000);
        main.stop();
    }
}