# deploy in zitadel namespace
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-minio-ca-issuer
spec:
  selfSigned: {}
---
# deploy in zitadel namespace
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-minio-cert
spec:
  commonName: minio.demo.com
  secretName: selfsigned-minio-cert-secret
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: selfsigned-minio-ca-issuer # issuer resource name
    kind: Issuer
  dnsNames:
---