# route.yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: tenant-route
spec:
  http:
    - name: tenant-console
      websocket: true
      match:
        hosts:
          - minio.demo.com
        paths:
          - "/*"
      backends:
        - serviceName: tenant-0-console
          servicePort: 9443
      #plugins:
      # - name: proxy-rewrite
      #   enable: true
      plugins:
       - name: proxy-rewrite
         enable: true
         config:
            scheme: https
       - name: redirect
         enable: true
         config:
            http_to_https: true
            https_port: 9443
       #     uri: ${uri}


          
