---
# deploy in zitadel namespace
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-postgre-ca-issuer
spec:
  selfSigned: {}
---
# deploy in zitadel namespace
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-postgres-cert
spec:
  commonName: postgres.demo.com  
  secretName: selfsigned-postgres-crt-secret
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: selfsigned-postgre-ca-issuer # issuer resource name
    kind: Issuer
  dnsNames:
    - postgres.demo.com  # dns name add this to hosts file for loopback address
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: postgres-op-tls
spec:
  hosts:
    - postgres.demo.com
  secret:
    name: selfsigned-postgres-crt-secret
    namespace: postgres-op
---